config/routes.rb
PetApp::Application.routes.draw do
  

  resources :vaccines

  resources :vaccinations

  resources :visits

  resources :animals
  resources :pets
  resources :owners
  resources :users
  resources :sessions

  root :to => 'pages#home'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/privacy', :to => 'pages#privacy'
  match '/signup', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
end

app/models/vaccination.rb
class Vaccination < ActiveRecord::Base
	attr_accessible :dosage, :vaccine_id, :visit_id

  belongs_to :vaccine
  belongs_to :visit

	
  validate :vaccine_offered_by_Joy_Veterinary_Services
  validate :vaccine_matches_animal_type 

	scope :for_vaccine, lambda{|vaccine_id| where('vaccine_id = ?', vaccine_id)} 
	scope :for_visit, lambda{|visit_id| where('visit_id = ?', visit_id)} 
	scope :chronological, joins(:visit).order('visit_date DESC') 
	scope :latest, lambda{|number| limit(number).joins(:visit).order('visit_date DESC')}

  private

	def vaccine_offered_by_Joy_Veterinary_Services
    vaccine_ids_list = Vaccine.all.map{|vaccine| vaccine.id}
    unless vaccine_ids_list.include?(self.vaccine_id)
      errors.add(:vaccine, "is not available at Joy Veterinary Services")
      return false
    end  
    
    return true
  end
  
  def vaccine_matches_animal_type
    animal = Visit.find(self.visit_id).pet.animal
    vaccine_ids_list = Vaccine.for_animal(animal.id).map{|vaccine| vaccine.id}
    unless vaccine_ids_list.include?(self.vaccine_id)
      errors.add(:vaccine, "is inappropriate for your animal")
      return false
    end  
    return true
  end      
      	
end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  # GET /vaccinations
  # GET /vaccinations.json
  def index
    @title = "Vaccination Listing"
    @vaccinations = Vaccination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vaccinations }
    end
  end

  # GET /vaccinations/1
  # GET /vaccinations/1.json
  def show
    @vaccination = Vaccination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vaccination }
    end
  end

  # GET /vaccinations/new
  # GET /vaccinations/new.json
  def new
    @title = "Register Vaccination"
    @vaccination = Vaccination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vaccination }
    end
  end

  # GET /vaccinations/1/edit
  def edit
    @vaccination = Vaccination.find(params[:id])
  end

  # POST /vaccinations
  # POST /vaccinations.json
  def create
    @vaccination = Vaccination.new(params[:vaccination])

    respond_to do |format|
      if @vaccination.save
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully created.' }
        format.json { render json: @vaccination, status: :created, location: @vaccination }
      else
        format.html { render action: "new" }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vaccinations/1
  # PUT /vaccinations/1.json
  def update
    @vaccination = Vaccination.find(params[:id])

    respond_to do |format|
      if @vaccination.update_attributes(params[:vaccination])
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccinations/1
  # DELETE /vaccinations/1.json
  def destroy
    @vaccination = Vaccination.find(params[:id])
    @vaccination.destroy

    respond_to do |format|
      format.html { redirect_to vaccinations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/vaccinations/_form.html.erb
<%= form_for(@vaccination) do |f| %>
  <% if @vaccination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccination.errors.count, "error") %> prohibited this vaccination from being saved:</h2>

      <ul>
      <% @vaccination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vaccine_id %><br />
    <%= collection_select(:vaccination, :vaccine_id, Vaccine.all, :id, :name) %>

  </div>
  <div class="field">
    <%= f.label :visit_id %><br />
    <%= collection_select(:vaccination, :visit_id, Visit.all, :id, :visit_date) %>

  </div>
  <div class="field">
    <%= f.label :dosage %><br />
    <%= f.text_field :dosage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccinations/edit.html.erb
<h1>Editing vaccination</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccination %> |
<%= link_to 'Back', vaccinations_path %>

app/views/vaccinations/index.html.erb
<h1>Listing Vaccinations</h1>
<%= link_to(image_tag("vac.jpg"), root_path) %>
<table id="Vaccination List">
  <tr>
    <th>Vaccine</th>
    <th>Visit</th>
    <th>Dosage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vaccinations.each do |vaccination| %>
  <tr>
    <td><%= vaccination.vaccine.name %></td>
    <td><%= vaccination.visit.visit_date %></td>
    <td><%= vaccination.dosage %></td>
    <td><%= link_to 'Show', vaccination %></td>
    <td><%= link_to 'Edit', edit_vaccination_path(vaccination) %></td>
    <td><%= link_to 'Destroy', vaccination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New Vaccination', new_vaccination_path %>

app/views/vaccinations/new.html.erb
<h1>New vaccination</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccinations_path %>

app/views/vaccinations/show.html.erb
<%= link_to(image_tag("vaccination.jpg"), root_path) %>
<p id="notice"><%= notice %></p>

<p>
  <b>Vaccine:</b>
  <%= @vaccination.vaccine_id %>
</p>

<p>
  <b>Visit:</b>
  <%= @vaccination.visit_id %>
</p>

<p>
  <b>Dosage:</b>
  <%= @vaccination.dosage %>
</p>


<%= link_to 'Edit', edit_vaccination_path(@vaccination) %> |
<%= link_to 'Back', vaccinations_path %>