config/routes.rb
PetApp::Application.routes.draw do
  

  resources :vaccines

  resources :vaccinations

  resources :visits

  resources :animals
  resources :pets
  resources :owners
  resources :users
  resources :sessions

  root :to => 'pages#home'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/privacy', :to => 'pages#privacy'
  match '/signup', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :notes, :pet_id, :visit_date, :weight
  
  belongs_to :pet
  has_many :vaccinations
  has_many :vaccines, :through => :vaccinations

  validates :pet_id, :weight, :visit_date, :presence => true 
  validates :weight, :numericality => {:greater_than => 0, :only_integer => true}

  scope :chronological, order('visit_date DESC')
  scope :for_pet, lambda{|pet_id| where('pet_id = ?', pet_id)}
  scope :latest, lambda{|number| limit(number).order('visit_date DESC')}

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
     @title = "Visit Listing"
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @title = "Log Visit"
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Your Visit was successfully recorded!' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :pet_id %><br />
    <%= collection_select(:visit, :pet_id, Pet.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :visit_date %><br />
    <%= f.date_select :visit_date %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing Visits</h1>
<%= link_to(image_tag("visit.png"), root_path) %>
<table id="Visit List">

  <tr>
    <th>Pet</th>
    <th>Visit Date</th>
    <th>Weight</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.pet.name %></td>
    <td><%= visit.visit_date %></td>
    <td><%= visit.weight %></td>
    <td><%= visit.notes %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
   <%= link_to(image_tag("visit_show.jpg"), root_path) %>
<p id="notice"><%= notice %></p>

<p>
  <b>Pet:</b>
  <%= @visit.pet_id %>
</p>

<p>
  <b>Visit date:</b>
  <%= @visit.visit_date %>
</p>

<p>
  <b>Weight:</b>
  <%= @visit.weight %>
</p>

<p>
  <b>Notes:</b>
  <%= @visit.notes %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>