config/routes.rb
PetApp::Application.routes.draw do
  

  resources :vaccines

  resources :vaccinations

  resources :visits

  resources :animals
  resources :pets
  resources :owners
  resources :users
  resources :sessions

  root :to => 'pages#home'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/privacy', :to => 'pages#privacy'
  match '/signup', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  attr_accessible :name
  has_many :pets
  has_many :vaccines

  validates :name, :presence => true
end
 

app/models/pet.rb
class Pet < ActiveRecord::Base
  attr_accessible :active, :animal_id, :date_of_birth, :female, :name, :owner_id
  belongs_to :animal
  belongs_to :owner
  has_many :visits

  validates :name, :presence => true

 	scope :alphabetical, order('name')
  	scope :active, where('active = ?', true)
	scope :female, where('female = ?', true)
	scope :male, where('female = ?', false)

scope :for_owner, lambda{|owner_id| where('owner_id = ?', owner_id)} 
scope :by_animal, lambda{|animal_id| where('animal_id = ?', animal_id)} 
scope :born_before, lambda{|date_of_birth| where('date_of_birth < ?', date_of_birth)} 
end

 

  

  

  
 
	
  

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_presence_of :password, :on => :create

end

app/models/vaccination.rb
class Vaccination < ActiveRecord::Base
	attr_accessible :dosage, :vaccine_id, :visit_id

  belongs_to :vaccine
  belongs_to :visit

	
  validate :vaccine_offered_by_Joy_Veterinary_Services
  validate :vaccine_matches_animal_type 

	scope :for_vaccine, lambda{|vaccine_id| where('vaccine_id = ?', vaccine_id)} 
	scope :for_visit, lambda{|visit_id| where('visit_id = ?', visit_id)} 
	scope :chronological, joins(:visit).order('visit_date DESC') 
	scope :latest, lambda{|number| limit(number).joins(:visit).order('visit_date DESC')}

  private

	def vaccine_offered_by_Joy_Veterinary_Services
    vaccine_ids_list = Vaccine.all.map{|vaccine| vaccine.id}
    unless vaccine_ids_list.include?(self.vaccine_id)
      errors.add(:vaccine, "is not available at Joy Veterinary Services")
      return false
    end  
    
    return true
  end
  
  def vaccine_matches_animal_type
    animal = Visit.find(self.visit_id).pet.animal
    vaccine_ids_list = Vaccine.for_animal(animal.id).map{|vaccine| vaccine.id}
    unless vaccine_ids_list.include?(self.vaccine_id)
      errors.add(:vaccine, "is inappropriate for your animal")
      return false
    end  
    return true
  end      
      	
end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
	attr_accessible :animal_id, :duration, :name
  
	before_save :check_vaccine_durability

	belongs_to :animal
	has_many :vaccinations
	has_many :visits, :through => :vaccinations
	
	validates :name, :animal_id, :presence => true 
	validates :duration, :numericality => {:greater_than => 0, :only_integer => true, :allow_blank => true, :allow_nil => true}

 	scope :alphabetical, order('name ASC')
 	scope :for_animal, lambda{|animal_id| where('animal_id = ?', animal_id)} 

 	private

 	def check_vaccine_durability
 		duration = self.duration
 		self.duration = 7305 if duration.nil? || duration.blank?
 	end	
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :notes, :pet_id, :visit_date, :weight
  
  belongs_to :pet
  has_many :vaccinations
  has_many :vaccines, :through => :vaccinations

  validates :pet_id, :weight, :visit_date, :presence => true 
  validates :weight, :numericality => {:greater_than => 0, :only_integer => true}

  scope :chronological, order('visit_date DESC')
  scope :for_pet, lambda{|pet_id| where('pet_id = ?', pet_id)}
  scope :latest, lambda{|number| limit(number).order('visit_date DESC')}

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end

  def about
  @title = "About Us"
  end

  def contact
  @title = "Contact Us"
  end

  def privacy
  @title = "Privacy Policy" 
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  # GET /pets.json
  def index
    @title = "Pet Listing"
    @pets = Pet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pets }
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = Pet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/new
  # GET /pets/new.json
  def new
    @title = "Pet Sign up"
    @pet = Pet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(params[:pet])

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Your Pet was successfully created!' }
        format.json { render json: @pet, status: :created, location: @pet }
      else
        format.html { render action: "new" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pets/1
  # PUT /pets/1.json
  def update
    @pet = Pet.find(params[:id])

    respond_to do |format|
      if @pet.update_attributes(params[:pet])
        format.html { redirect_to @pet, notice: 'Your Pet was successfully updated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
      @title = "Sign up"
    	@user = User.new
  	end 

	def create
   		@user = User.new(params[:user])
    	if @user.save
      	redirect_to root_url, :notice => "Signed up!"
    	else
      	render "new"
    	end
  	end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.

	def full_title
  		@title ? "Pet App | #{@title}" : "Pet App| TM"
  	end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Online Pet Application", home_path, id: "logo" %>
          <%= link_to(image_tag("fb.png"),"https://www.facebook.com/schaxz") %>
          <%= link_to(image_tag("tw.png"),"https://twitter.com/Srinjoy_Chakrav") %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "About Us",   about_path %></li>
              <li><%= link_to "Contact Us", contact_path %></li>
              <li><%= link_to "Privacy Policy", privacy_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header> 
    <% flash.each do |name, msg| %>

    <% end %>
    <div class="container">
      <%= yield %>
      <footer class="footer">
        <small>
          <a href="http://qats.herokuapp.com">Strictly copyrighted to QATS Pet App ©</a>
        </small>
        <nav>
          <ul>
             <li><%= link_to(image_tag("home.png"), root_path) %></li>
             <li><%= link_to(image_tag("about.png"), about_path) %></li>
             <li><%= link_to(image_tag("contact.png"), contact_path) %></li>
             <li><%= link_to(image_tag("privacy.png"), privacy_path) %></li>
             <li><a href="https://twitter.com/Srinjoy_Chakrav"> Webmaster: Srinjoy Chakravarty   © 2012</a>
             </li>
          </ul>
              <%= link_to(image_tag("dog.png"),home_path) %>
        </nav>
      </footer>
    </div>
  </body>
</html>